---

- name: Create a directory if it does not exist
  file:
    path: /etc/nacho
    state: directory
    mode: '0755'

- name: Touch a file
  file:
    path: /etc/nacho/foo.conf
    state: touch
    mode: u=rw,g=r,o=r