---
- name: Configure Web servers
  hosts: "{{ group }}" # host group in inventory file
  user: root
  
  roles:
    - file
    - apache
    - foo
    - nginx
    - dependancies
    - checks
    - cleanups